import { NextRequest, NextResponse } from "next/server";
// @ts-ignore — pptxgenjs has no bundled types that work perfectly in all TS configs
import pptxgen from "pptxgenjs";

type Style = "minimal" | "academic" | "pitch";

interface TitleSlide {
  slideNumber: number;
  type: "title";
  title: string;
  subtitle: string;
  notes: string;
}
interface AgendaSlide {
  slideNumber: number;
  type: "agenda";
  title: string;
  points: string[];
  notes: string;
}
interface ContentSlide {
  slideNumber: number;
  type: "content";
  title: string;
  bullets: string[];
  highlight: string;
  notes: string;
}
interface SummarySlide {
  slideNumber: number;
  type: "summary";
  title: string;
  bullets: string[];
  notes: string;
}

type Slide = TitleSlide | AgendaSlide | ContentSlide | SummarySlide;

interface ClaudeResponse {
  title: string;
  subtitle: string;
  presenter: string;
  slides: Slide[];
}

// ─── Color palettes ───────────────────────────────────────────────────────────

const ORCHID = "c96acb";
const BLACK = "050505";
const DARK = "0a0a0a";
const GRAY_HEADER = "1a1a1a";
const WHITE = "ffffff";
const BODY_GRAY = "a1a1aa";
const ZINC = "52525b";

// pptxgenjs exposes shape constants as a static-like object on the imported
// module itself (not on slide/presentation instances). Using `as any` here
// keeps this resilient across pptxgenjs versions where the exact type
// export changes.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const ShapeType: any = (pptxgen as any).ShapeType;

function buildMinimal(pres: InstanceType<typeof pptxgen>, slides: Slide[]) {
  for (const slide of slides) {
    const s = pres.addSlide();
    s.background = { color: BLACK };

    if (slide.type === "title") {
      const ts = slide as TitleSlide;
      s.addText(ts.title, {
        x: 0.6, y: 1.5, w: 8.8, h: 1.5,
        fontSize: 40, bold: true, color: WHITE, fontFace: "Calibri",
        align: "center", valign: "middle",
      });
      s.addText(ts.subtitle, {
        x: 1, y: 3.2, w: 8, h: 0.8,
        fontSize: 18, color: BODY_GRAY, fontFace: "Calibri",
        align: "center", valign: "middle",
      });
      s.addText("Generated by Memo", {
        x: 7, y: 5.1, w: 2.7, h: 0.3,
        fontSize: 10, color: ZINC, fontFace: "Calibri", align: "right",
      });
    } else if (slide.type === "agenda") {
      const ag = slide as AgendaSlide;
      s.addText(ag.title, {
        x: 0.6, y: 0.4, w: 8.8, h: 0.7,
        fontSize: 28, bold: true, color: WHITE, fontFace: "Calibri",
      });
      s.addShape(ShapeType.rect, {
        x: 0.6, y: 1.2, w: 8.8, h: 0.02,
        fill: { color: ORCHID, transparency: 40 },
        line: { color: ORCHID, width: 0 },
      });
      const bulletItems = ag.points.map((pt, i) => ({
        text: `${i + 1}.  ${pt}`,
        options: { breakLine: true, color: BODY_GRAY, fontSize: 17 },
      }));
      bulletItems[bulletItems.length - 1].options.breakLine = false as never;
      s.addText(bulletItems, {
        x: 0.8, y: 1.5, w: 8.4, h: 3.5,
        fontFace: "Calibri", valign: "top",
      });
    } else if (slide.type === "content") {
      const cs = slide as ContentSlide;
      s.addText(cs.title, {
        x: 0.6, y: 0.4, w: 8.8, h: 0.7,
        fontSize: 24, bold: true, color: WHITE, fontFace: "Calibri",
      });
      s.addShape(ShapeType.rect, {
        x: 0.6, y: 1.2, w: 8.8, h: 0.02,
        fill: { color: ORCHID, transparency: 40 },
        line: { color: ORCHID, width: 0 },
      });
      const bulletItems = cs.bullets.map((b, i) => ({
        text: b,
        options: {
          bullet: true,
          breakLine: i < cs.bullets.length - 1,
          color: BODY_GRAY,
          fontSize: 16,
          paraSpaceAfter: 4,
        } as Record<string, unknown>,
      }));
      s.addText(bulletItems as Parameters<typeof s.addText>[0], {
        x: 0.8, y: 1.5, w: 8.4, h: 2.8,
        fontFace: "Calibri", valign: "top",
      });
      if (cs.highlight) {
        s.addText(cs.highlight, {
          x: 0.6, y: 4.5, w: 8.8, h: 0.8,
          fontSize: 15, color: ORCHID, fontFace: "Calibri",
          italic: true, align: "left",
        });
      }
    } else if (slide.type === "summary") {
      const ss = slide as SummarySlide;
      s.addText(ss.title || "Key Takeaways", {
        x: 0.6, y: 0.4, w: 8.8, h: 0.7,
        fontSize: 28, bold: true, color: WHITE, fontFace: "Calibri",
      });
      s.addShape(ShapeType.rect, {
        x: 0.6, y: 1.2, w: 8.8, h: 0.02,
        fill: { color: ORCHID, transparency: 40 },
        line: { color: ORCHID, width: 0 },
      });
      const bulletItems = (ss.bullets || []).map((b, i) => ({
        text: b,
        options: {
          bullet: true,
          breakLine: i < (ss.bullets || []).length - 1,
          color: WHITE,
          fontSize: 17,
          bold: true,
          paraSpaceAfter: 6,
        } as Record<string, unknown>,
      }));
      s.addText(bulletItems as Parameters<typeof s.addText>[0], {
        x: 0.8, y: 1.5, w: 8.4, h: 3.5,
        fontFace: "Calibri", valign: "top",
      });
    }

    if (slide.notes) s.addNotes(slide.notes);
  }
}

function buildAcademic(pres: InstanceType<typeof pptxgen>, slides: Slide[]) {
  for (const slide of slides) {
    const s = pres.addSlide();
    s.background = { color: DARK };

    const isTitle = slide.type === "title";
    if (!isTitle) {
      // Header bar
      s.addShape(ShapeType.rect, {
        x: 0, y: 0, w: 10, h: 0.85,
        fill: { color: GRAY_HEADER },
        line: { color: GRAY_HEADER, width: 0 },
      });
      s.addText(slide.title, {
        x: 0.4, y: 0, w: 9.2, h: 0.85,
        fontSize: 20, bold: true, color: WHITE, fontFace: "Calibri",
        valign: "middle", margin: 0,
      });
      // Slide number bottom right
      s.addText(String(slide.slideNumber), {
        x: 9.3, y: 5.2, w: 0.5, h: 0.25,
        fontSize: 10, color: ZINC, fontFace: "Calibri", align: "right",
      });
    }

    if (slide.type === "title") {
      const ts = slide as TitleSlide;
      s.addText(ts.title, {
        x: 0.8, y: 1.4, w: 8.4, h: 1.5,
        fontSize: 32, bold: true, color: WHITE, fontFace: "Calibri",
        align: "center", valign: "middle",
      });
      s.addText(ts.subtitle, {
        x: 1, y: 3.0, w: 8, h: 0.8,
        fontSize: 16, color: BODY_GRAY, fontFace: "Calibri",
        align: "center",
      });
      s.addText("Generated by Memo", {
        x: 7, y: 5.1, w: 2.7, h: 0.3,
        fontSize: 10, color: ZINC, fontFace: "Calibri", align: "right",
      });
    } else if (slide.type === "agenda") {
      const ag = slide as AgendaSlide;
      const bulletItems = ag.points.map((pt, i) => ({
        text: `${i + 1}.  ${pt}`,
        options: { breakLine: true, color: WHITE, fontSize: 16, paraSpaceAfter: 4 },
      }));
      bulletItems[bulletItems.length - 1].options.breakLine = false as never;
      s.addText(bulletItems, { x: 0.6, y: 1.1, w: 8.8, h: 4.2, fontFace: "Calibri", valign: "top" });
    } else if (slide.type === "content") {
      const cs = slide as ContentSlide;
      const bulletItems = cs.bullets.map((b, i) => ({
        text: b,
        options: {
          bullet: true,
          breakLine: i < cs.bullets.length - 1,
          color: WHITE,
          fontSize: 15,
          paraSpaceAfter: 3,
        } as Record<string, unknown>,
      }));
      s.addText(bulletItems as Parameters<typeof s.addText>[0], {
        x: 0.6, y: 1.1, w: 8.8, h: 3.2,
        fontFace: "Calibri", valign: "top",
      });
      if (cs.highlight) {
        s.addShape(ShapeType.roundRect, {
          x: 0.6, y: 4.4, w: 8.8, h: 0.85,
          fill: { color: "1a1a1a" },
          line: { color: ORCHID, width: 1 },
          rectRadius: 0.05,
        });
        s.addText(cs.highlight, {
          x: 0.8, y: 4.45, w: 8.4, h: 0.75,
          fontSize: 13, color: ORCHID, fontFace: "Calibri",
          italic: true, valign: "middle",
        });
      }
    } else if (slide.type === "summary") {
      const ss = slide as SummarySlide;
      const bulletItems = (ss.bullets || []).map((b, i) => ({
        text: b,
        options: {
          bullet: true,
          breakLine: i < (ss.bullets || []).length - 1,
          color: WHITE,
          fontSize: 16,
          bold: true,
          paraSpaceAfter: 5,
        } as Record<string, unknown>,
      }));
      s.addText(bulletItems as Parameters<typeof s.addText>[0], {
        x: 0.6, y: 1.1, w: 8.8, h: 4.2,
        fontFace: "Calibri", valign: "top",
      });
    }

    if (slide.notes) s.addNotes(slide.notes);
  }
}

function buildPitch(pres: InstanceType<typeof pptxgen>, slides: Slide[]) {
  for (const slide of slides) {
    const s = pres.addSlide();
    s.background = { color: BLACK };

    // Bottom bar for all slides
    s.addShape(ShapeType.rect, {
      x: 0, y: 5.3, w: 10, h: 0.325,
      fill: { color: ORCHID },
      line: { color: ORCHID, width: 0 },
    });

    if (slide.type === "title") {
      const ts = slide as TitleSlide;
      s.addText(ts.title, {
        x: 0.5, y: 0.9, w: 9, h: 2.0,
        fontSize: 44, bold: true, color: WHITE, fontFace: "Calibri",
        align: "center", valign: "middle",
      });
      s.addText(ts.subtitle, {
        x: 1, y: 3.1, w: 8, h: 0.9,
        fontSize: 20, color: ORCHID, fontFace: "Calibri",
        align: "center", bold: true,
      });
      s.addText("Generated by Memo", {
        x: 0, y: 4.9, w: 9.8, h: 0.3,
        fontSize: 10, color: ZINC, fontFace: "Calibri", align: "right",
      });
    } else if (slide.type === "agenda") {
      const ag = slide as AgendaSlide;
      s.addText(ag.title, {
        x: 0.5, y: 0.3, w: 9, h: 0.9,
        fontSize: 36, bold: true, color: WHITE, fontFace: "Calibri",
        align: "center",
      });
      const bulletItems = ag.points.map((pt, i) => ({
        text: `${i + 1}  ${pt}`,
        options: { breakLine: true, color: BODY_GRAY, fontSize: 18, paraSpaceAfter: 6 },
      }));
      bulletItems[bulletItems.length - 1].options.breakLine = false as never;
      s.addText(bulletItems, {
        x: 1.5, y: 1.4, w: 7, h: 3.5,
        fontFace: "Calibri", align: "center", valign: "top",
      });
    } else if (slide.type === "content") {
      const cs = slide as ContentSlide;
      s.addText(cs.title, {
        x: 0.5, y: 0.25, w: 9, h: 0.9,
        fontSize: 32, bold: true, color: WHITE, fontFace: "Calibri",
        align: "center",
      });
      if (cs.highlight) {
        s.addText(cs.highlight, {
          x: 0.8, y: 1.3, w: 8.4, h: 1.1,
          fontSize: 22, color: ORCHID, fontFace: "Calibri",
          bold: true, align: "center", valign: "middle",
        });
      }
      // Single strong bullet or first bullet only — pitch style is lean
      const mainBullet = cs.bullets[0] || "";
      if (mainBullet) {
        s.addText(mainBullet, {
          x: 1, y: 2.6, w: 8, h: 0.8,
          fontSize: 17, color: BODY_GRAY, fontFace: "Calibri",
          align: "center",
        });
      }
    } else if (slide.type === "summary") {
      const ss = slide as SummarySlide;
      s.addText(ss.title || "Key Takeaways", {
        x: 0.5, y: 0.25, w: 9, h: 0.9,
        fontSize: 36, bold: true, color: WHITE, fontFace: "Calibri",
        align: "center",
      });
      const bulletItems = (ss.bullets || []).map((b, i) => ({
        text: b,
        options: {
          bullet: true,
          breakLine: i < (ss.bullets || []).length - 1,
          color: WHITE,
          fontSize: 18,
          bold: true,
          paraSpaceAfter: 8,
        } as Record<string, unknown>,
      }));
      s.addText(bulletItems as Parameters<typeof s.addText>[0], {
        x: 1.5, y: 1.4, w: 7, h: 3.5,
        fontFace: "Calibri", align: "center", valign: "top",
      });
    }

    if (slide.notes) s.addNotes(slide.notes);
  }
}

// ─── Route ────────────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { transcript, style }: { transcript: string; style: Style } = body;

    if (!transcript || !style) {
      return NextResponse.json({ error: "Missing transcript or style" }, { status: 400 });
    }

    // ── Step 1: Claude call ────────────────────────────────────────────────────
    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY!,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-20250514",
        max_tokens: 3000,
        system:
          "You are a presentation builder. Return ONLY valid JSON — no markdown fences, no preamble, no explanation. Follow the schema exactly.",
        messages: [
          {
            role: "user",
            content: `Analyse this transcript and return a JSON object with this EXACT structure:

{
  "title": "session title, 4-8 words",
  "subtitle": "one line description of what was covered",
  "presenter": "Memo AI",
  "slides": [
    {
      "slideNumber": 1,
      "type": "title",
      "title": "string",
      "subtitle": "string",
      "notes": "speaker notes"
    },
    {
      "slideNumber": 2,
      "type": "agenda",
      "title": "Agenda",
      "points": ["string", "string", "string"],
      "notes": "string"
    },
    {
      "slideNumber": 3,
      "type": "content",
      "title": "concept name",
      "bullets": ["key point (max 8 words)", "key point", "key point"],
      "highlight": "one sentence most important takeaway",
      "notes": "speaker notes for this slide"
    }
    // ... more content slides, one per key concept
    // last slide MUST be type "summary"
  ]
}

Rules:
- Minimum 6 slides, maximum 14 slides
- ALWAYS start with type "title" then type "agenda"
- One type "content" slide per key concept found in the transcript
- ALWAYS end with type "summary" containing "bullets" array of 3-5 key takeaways
- summary slide has "title", "bullets", "notes" — no "highlight" field
- Speaker notes on every slide
- Bullets max 8 words each
- Title is punchy and descriptive

TRANSCRIPT:
${transcript.slice(0, 6000)}`,
          },
        ],
      }),
    });

    if (!claudeRes.ok) {
      const err = await claudeRes.text();
      return NextResponse.json({ error: `Claude error: ${err}` }, { status: 500 });
    }

    const claudeData = await claudeRes.json();
    const rawText: string = claudeData.content
      .filter((c: { type: string }) => c.type === "text")
      .map((c: { text: string }) => c.text)
      .join("");

    let parsed: ClaudeResponse;
    try {
      const clean = rawText.replace(/```json|```/g, "").trim();
      parsed = JSON.parse(clean);
    } catch {
      return NextResponse.json({ error: "Failed to parse Claude response as JSON" }, { status: 500 });
    }

    // ── Step 2: Build PPTX ─────────────────────────────────────────────────────
    const pres = new pptxgen();
    pres.layout = "LAYOUT_16x9";
    pres.author = "Memo AI";
    pres.title = parsed.title;

    if (style === "minimal") {
      buildMinimal(pres, parsed.slides);
    } else if (style === "academic") {
      buildAcademic(pres, parsed.slides);
    } else {
      buildPitch(pres, parsed.slides);
    }

    const pptxBuffer: ArrayBuffer = await pres.write({ outputType: "arraybuffer" });
    const pptxBase64 = Buffer.from(pptxBuffer).toString("base64");

    // ── Step 3: Return ─────────────────────────────────────────────────────────
    return NextResponse.json({
      pptxBase64,
      slideCount: parsed.slides.length,
      title: parsed.title,
      slides: parsed.slides.map((s) => ({
        slideNumber: s.slideNumber,
        title: s.title,
        type: s.type,
      })),
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Unknown error";
    console.error("[generate-presentation]", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}